// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nuser.proto

package NUserPb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ActionType int32

const (
	ActionType_Register_Type    ActionType = 0
	ActionType_Retrieve_Type    ActionType = 1
	ActionType_Login_Type       ActionType = 2
	ActionType_EmailAttest_Type ActionType = 3
)

var ActionType_name = map[int32]string{
	0: "Register_Type",
	1: "Retrieve_Type",
	2: "Login_Type",
	3: "EmailAttest_Type",
}

var ActionType_value = map[string]int32{
	"Register_Type":    0,
	"Retrieve_Type":    1,
	"Login_Type":       2,
	"EmailAttest_Type": 3,
}

func (x ActionType) String() string {
	return proto.EnumName(ActionType_name, int32(x))
}

func (ActionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_70be6522ed124f25, []int{0}
}

type ChangeNumResponse struct {
	Count                uint32   `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeNumResponse) Reset()         { *m = ChangeNumResponse{} }
func (m *ChangeNumResponse) String() string { return proto.CompactTextString(m) }
func (*ChangeNumResponse) ProtoMessage()    {}
func (*ChangeNumResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_70be6522ed124f25, []int{0}
}

func (m *ChangeNumResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeNumResponse.Unmarshal(m, b)
}
func (m *ChangeNumResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeNumResponse.Marshal(b, m, deterministic)
}
func (m *ChangeNumResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeNumResponse.Merge(m, src)
}
func (m *ChangeNumResponse) XXX_Size() int {
	return xxx_messageInfo_ChangeNumResponse.Size(m)
}
func (m *ChangeNumResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeNumResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeNumResponse proto.InternalMessageInfo

func (m *ChangeNumResponse) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type UserLoginRequest struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLoginRequest) Reset()         { *m = UserLoginRequest{} }
func (m *UserLoginRequest) String() string { return proto.CompactTextString(m) }
func (*UserLoginRequest) ProtoMessage()    {}
func (*UserLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_70be6522ed124f25, []int{1}
}

func (m *UserLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLoginRequest.Unmarshal(m, b)
}
func (m *UserLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLoginRequest.Marshal(b, m, deterministic)
}
func (m *UserLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLoginRequest.Merge(m, src)
}
func (m *UserLoginRequest) XXX_Size() int {
	return xxx_messageInfo_UserLoginRequest.Size(m)
}
func (m *UserLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserLoginRequest proto.InternalMessageInfo

func (m *UserLoginRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *UserLoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type SMSLoginRequest struct {
	Tel                  string   `protobuf:"bytes,1,opt,name=tel,proto3" json:"tel,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SMSLoginRequest) Reset()         { *m = SMSLoginRequest{} }
func (m *SMSLoginRequest) String() string { return proto.CompactTextString(m) }
func (*SMSLoginRequest) ProtoMessage()    {}
func (*SMSLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_70be6522ed124f25, []int{2}
}

func (m *SMSLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SMSLoginRequest.Unmarshal(m, b)
}
func (m *SMSLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SMSLoginRequest.Marshal(b, m, deterministic)
}
func (m *SMSLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SMSLoginRequest.Merge(m, src)
}
func (m *SMSLoginRequest) XXX_Size() int {
	return xxx_messageInfo_SMSLoginRequest.Size(m)
}
func (m *SMSLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SMSLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SMSLoginRequest proto.InternalMessageInfo

func (m *SMSLoginRequest) GetTel() string {
	if m != nil {
		return m.Tel
	}
	return ""
}

func (m *SMSLoginRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type UserInfo struct {
	Uid                  uint64   `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Alias                string   `protobuf:"bytes,3,opt,name=alias,proto3" json:"alias,omitempty"`
	Tel                  string   `protobuf:"bytes,4,opt,name=Tel,proto3" json:"Tel,omitempty"`
	Email                string   `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Status               uint32   `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	EmailStatus          uint32   `protobuf:"varint,7,opt,name=email_status,json=emailStatus,proto3" json:"email_status,omitempty"`
	Password             string   `protobuf:"bytes,8,opt,name=password,proto3" json:"password,omitempty"`
	CreatedAt            uint64   `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            uint64   `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            uint64   `protobuf:"varint,11,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_70be6522ed124f25, []int{3}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *UserInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserInfo) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *UserInfo) GetTel() string {
	if m != nil {
		return m.Tel
	}
	return ""
}

func (m *UserInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserInfo) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *UserInfo) GetEmailStatus() uint32 {
	if m != nil {
		return m.EmailStatus
	}
	return 0
}

func (m *UserInfo) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserInfo) GetCreatedAt() uint64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *UserInfo) GetUpdatedAt() uint64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *UserInfo) GetDeletedAt() uint64 {
	if m != nil {
		return m.DeletedAt
	}
	return 0
}

type Token struct {
	AccountToken         string   `protobuf:"bytes,1,opt,name=account_token,json=accountToken,proto3" json:"account_token,omitempty"`
	RefreshToken         string   `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_70be6522ed124f25, []int{4}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetAccountToken() string {
	if m != nil {
		return m.AccountToken
	}
	return ""
}

func (m *Token) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type LoginResponse struct {
	Info                 *UserInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Token                *Token    `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_70be6522ed124f25, []int{5}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetInfo() *UserInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *LoginResponse) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

type NilResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NilResponse) Reset()         { *m = NilResponse{} }
func (m *NilResponse) String() string { return proto.CompactTextString(m) }
func (*NilResponse) ProtoMessage()    {}
func (*NilResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_70be6522ed124f25, []int{6}
}

func (m *NilResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NilResponse.Unmarshal(m, b)
}
func (m *NilResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NilResponse.Marshal(b, m, deterministic)
}
func (m *NilResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NilResponse.Merge(m, src)
}
func (m *NilResponse) XXX_Size() int {
	return xxx_messageInfo_NilResponse.Size(m)
}
func (m *NilResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NilResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NilResponse proto.InternalMessageInfo

type UserRegisterRequest struct {
	Info                 *UserInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Code                 string    `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UserRegisterRequest) Reset()         { *m = UserRegisterRequest{} }
func (m *UserRegisterRequest) String() string { return proto.CompactTextString(m) }
func (*UserRegisterRequest) ProtoMessage()    {}
func (*UserRegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_70be6522ed124f25, []int{7}
}

func (m *UserRegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRegisterRequest.Unmarshal(m, b)
}
func (m *UserRegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRegisterRequest.Marshal(b, m, deterministic)
}
func (m *UserRegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRegisterRequest.Merge(m, src)
}
func (m *UserRegisterRequest) XXX_Size() int {
	return xxx_messageInfo_UserRegisterRequest.Size(m)
}
func (m *UserRegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRegisterRequest proto.InternalMessageInfo

func (m *UserRegisterRequest) GetInfo() *UserInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *UserRegisterRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type SendRequest struct {
	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	//0为注册邮件验证发送邮件；1为找回密码发送邮件验证 2为登录 3为邮箱验证
	Type                 ActionType `protobuf:"varint,2,opt,name=type,proto3,enum=NUserPb.ActionType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SendRequest) Reset()         { *m = SendRequest{} }
func (m *SendRequest) String() string { return proto.CompactTextString(m) }
func (*SendRequest) ProtoMessage()    {}
func (*SendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_70be6522ed124f25, []int{8}
}

func (m *SendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendRequest.Unmarshal(m, b)
}
func (m *SendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendRequest.Marshal(b, m, deterministic)
}
func (m *SendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendRequest.Merge(m, src)
}
func (m *SendRequest) XXX_Size() int {
	return xxx_messageInfo_SendRequest.Size(m)
}
func (m *SendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendRequest proto.InternalMessageInfo

func (m *SendRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *SendRequest) GetType() ActionType {
	if m != nil {
		return m.Type
	}
	return ActionType_Register_Type
}

type CheckCodeRequest struct {
	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Code    string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	//0为注册邮件验证发送邮件；1为找回密码发送邮件验证 2为登录 3为邮箱验证
	Type                 ActionType `protobuf:"varint,3,opt,name=type,proto3,enum=NUserPb.ActionType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CheckCodeRequest) Reset()         { *m = CheckCodeRequest{} }
func (m *CheckCodeRequest) String() string { return proto.CompactTextString(m) }
func (*CheckCodeRequest) ProtoMessage()    {}
func (*CheckCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_70be6522ed124f25, []int{9}
}

func (m *CheckCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckCodeRequest.Unmarshal(m, b)
}
func (m *CheckCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckCodeRequest.Marshal(b, m, deterministic)
}
func (m *CheckCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckCodeRequest.Merge(m, src)
}
func (m *CheckCodeRequest) XXX_Size() int {
	return xxx_messageInfo_CheckCodeRequest.Size(m)
}
func (m *CheckCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckCodeRequest proto.InternalMessageInfo

func (m *CheckCodeRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *CheckCodeRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *CheckCodeRequest) GetType() ActionType {
	if m != nil {
		return m.Type
	}
	return ActionType_Register_Type
}

type RetrievePasswordRequest struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Code                 string   `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetrievePasswordRequest) Reset()         { *m = RetrievePasswordRequest{} }
func (m *RetrievePasswordRequest) String() string { return proto.CompactTextString(m) }
func (*RetrievePasswordRequest) ProtoMessage()    {}
func (*RetrievePasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_70be6522ed124f25, []int{10}
}

func (m *RetrievePasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrievePasswordRequest.Unmarshal(m, b)
}
func (m *RetrievePasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrievePasswordRequest.Marshal(b, m, deterministic)
}
func (m *RetrievePasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrievePasswordRequest.Merge(m, src)
}
func (m *RetrievePasswordRequest) XXX_Size() int {
	return xxx_messageInfo_RetrievePasswordRequest.Size(m)
}
func (m *RetrievePasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrievePasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RetrievePasswordRequest proto.InternalMessageInfo

func (m *RetrievePasswordRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *RetrievePasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RetrievePasswordRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type PageRequest struct {
	Keyword              string   `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Page                 uint32   `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit                uint32   `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	IsDelete             bool     `protobuf:"varint,4,opt,name=is_delete,json=isDelete,proto3" json:"is_delete,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageRequest) Reset()         { *m = PageRequest{} }
func (m *PageRequest) String() string { return proto.CompactTextString(m) }
func (*PageRequest) ProtoMessage()    {}
func (*PageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_70be6522ed124f25, []int{11}
}

func (m *PageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageRequest.Unmarshal(m, b)
}
func (m *PageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageRequest.Marshal(b, m, deterministic)
}
func (m *PageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageRequest.Merge(m, src)
}
func (m *PageRequest) XXX_Size() int {
	return xxx_messageInfo_PageRequest.Size(m)
}
func (m *PageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PageRequest proto.InternalMessageInfo

func (m *PageRequest) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

func (m *PageRequest) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *PageRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *PageRequest) GetIsDelete() bool {
	if m != nil {
		return m.IsDelete
	}
	return false
}

type UserListResponse struct {
	List                 []*UserInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Count                uint32      `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UserListResponse) Reset()         { *m = UserListResponse{} }
func (m *UserListResponse) String() string { return proto.CompactTextString(m) }
func (*UserListResponse) ProtoMessage()    {}
func (*UserListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_70be6522ed124f25, []int{12}
}

func (m *UserListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserListResponse.Unmarshal(m, b)
}
func (m *UserListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserListResponse.Marshal(b, m, deterministic)
}
func (m *UserListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserListResponse.Merge(m, src)
}
func (m *UserListResponse) XXX_Size() int {
	return xxx_messageInfo_UserListResponse.Size(m)
}
func (m *UserListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserListResponse proto.InternalMessageInfo

func (m *UserListResponse) GetList() []*UserInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *UserListResponse) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type UidList struct {
	Uid                  []uint32 `protobuf:"varint,1,rep,packed,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UidList) Reset()         { *m = UidList{} }
func (m *UidList) String() string { return proto.CompactTextString(m) }
func (*UidList) ProtoMessage()    {}
func (*UidList) Descriptor() ([]byte, []int) {
	return fileDescriptor_70be6522ed124f25, []int{13}
}

func (m *UidList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UidList.Unmarshal(m, b)
}
func (m *UidList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UidList.Marshal(b, m, deterministic)
}
func (m *UidList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UidList.Merge(m, src)
}
func (m *UidList) XXX_Size() int {
	return xxx_messageInfo_UidList.Size(m)
}
func (m *UidList) XXX_DiscardUnknown() {
	xxx_messageInfo_UidList.DiscardUnknown(m)
}

var xxx_messageInfo_UidList proto.InternalMessageInfo

func (m *UidList) GetUid() []uint32 {
	if m != nil {
		return m.Uid
	}
	return nil
}

type UserList struct {
	List                 []*UserInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UserList) Reset()         { *m = UserList{} }
func (m *UserList) String() string { return proto.CompactTextString(m) }
func (*UserList) ProtoMessage()    {}
func (*UserList) Descriptor() ([]byte, []int) {
	return fileDescriptor_70be6522ed124f25, []int{14}
}

func (m *UserList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserList.Unmarshal(m, b)
}
func (m *UserList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserList.Marshal(b, m, deterministic)
}
func (m *UserList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserList.Merge(m, src)
}
func (m *UserList) XXX_Size() int {
	return xxx_messageInfo_UserList.Size(m)
}
func (m *UserList) XXX_DiscardUnknown() {
	xxx_messageInfo_UserList.DiscardUnknown(m)
}

var xxx_messageInfo_UserList proto.InternalMessageInfo

func (m *UserList) GetList() []*UserInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterEnum("NUserPb.ActionType", ActionType_name, ActionType_value)
	proto.RegisterType((*ChangeNumResponse)(nil), "NUserPb.ChangeNumResponse")
	proto.RegisterType((*UserLoginRequest)(nil), "NUserPb.UserLoginRequest")
	proto.RegisterType((*SMSLoginRequest)(nil), "NUserPb.SMSLoginRequest")
	proto.RegisterType((*UserInfo)(nil), "NUserPb.UserInfo")
	proto.RegisterType((*Token)(nil), "NUserPb.Token")
	proto.RegisterType((*LoginResponse)(nil), "NUserPb.LoginResponse")
	proto.RegisterType((*NilResponse)(nil), "NUserPb.NilResponse")
	proto.RegisterType((*UserRegisterRequest)(nil), "NUserPb.UserRegisterRequest")
	proto.RegisterType((*SendRequest)(nil), "NUserPb.SendRequest")
	proto.RegisterType((*CheckCodeRequest)(nil), "NUserPb.CheckCodeRequest")
	proto.RegisterType((*RetrievePasswordRequest)(nil), "NUserPb.RetrievePasswordRequest")
	proto.RegisterType((*PageRequest)(nil), "NUserPb.PageRequest")
	proto.RegisterType((*UserListResponse)(nil), "NUserPb.UserListResponse")
	proto.RegisterType((*UidList)(nil), "NUserPb.UidList")
	proto.RegisterType((*UserList)(nil), "NUserPb.UserList")
}

func init() { proto.RegisterFile("nuser.proto", fileDescriptor_70be6522ed124f25) }

var fileDescriptor_70be6522ed124f25 = []byte{
	// 898 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xdd, 0x6f, 0xe3, 0x44,
	0x10, 0x4f, 0x9b, 0xb4, 0x71, 0xc6, 0x71, 0xcf, 0xdd, 0x2b, 0x87, 0xc9, 0x81, 0x74, 0x2c, 0x20,
	0x0e, 0x1e, 0x2a, 0x08, 0x42, 0x15, 0x48, 0x54, 0xa4, 0xe9, 0x09, 0x4e, 0xba, 0x2b, 0xc1, 0x49,
	0x10, 0x0f, 0x48, 0x91, 0xcf, 0x9e, 0xa4, 0xab, 0x3a, 0x76, 0xf0, 0x6e, 0x8a, 0xf2, 0xef, 0xf0,
	0x57, 0xf2, 0x88, 0xf6, 0x23, 0xb6, 0xf3, 0x75, 0xb9, 0xc2, 0x53, 0x3c, 0x1f, 0xbf, 0x99, 0xdd,
	0x99, 0xdf, 0xcc, 0x06, 0xec, 0x64, 0xce, 0x31, 0x3b, 0x9f, 0x65, 0xa9, 0x48, 0x49, 0xfd, 0x66,
	0xc8, 0x31, 0xeb, 0xbd, 0xa1, 0x5f, 0xc0, 0x69, 0xf7, 0x36, 0x48, 0x26, 0x78, 0x33, 0x9f, 0xfa,
	0xc8, 0x67, 0x69, 0xc2, 0x91, 0x9c, 0xc1, 0x51, 0x98, 0xce, 0x13, 0xe1, 0x1d, 0x3c, 0x3b, 0x78,
	0xee, 0xf8, 0x5a, 0xa0, 0x3f, 0x83, 0x2b, 0x41, 0xaf, 0xd2, 0x09, 0x4b, 0x7c, 0xfc, 0x73, 0x8e,
	0x5c, 0x10, 0x0f, 0xea, 0x41, 0x58, 0xf8, 0x36, 0xfc, 0xa5, 0x48, 0x5a, 0x60, 0xcd, 0x02, 0xce,
	0xff, 0x4a, 0xb3, 0xc8, 0x3b, 0x54, 0xa6, 0x5c, 0xa6, 0x17, 0xf0, 0xa8, 0xff, 0xba, 0xbf, 0x12,
	0xc8, 0x85, 0xaa, 0xc0, 0xd8, 0x04, 0x91, 0x9f, 0x84, 0x40, 0x2d, 0x4c, 0x23, 0x34, 0x60, 0xf5,
	0x4d, 0xff, 0x3e, 0x04, 0x4b, 0x9e, 0xe1, 0x65, 0x32, 0x4e, 0x25, 0x64, 0xce, 0x22, 0x05, 0xa9,
	0xf9, 0xf2, 0x53, 0x42, 0x92, 0x60, 0x9a, 0x43, 0xe4, 0xb7, 0xbc, 0x4b, 0x10, 0xb3, 0x80, 0x7b,
	0x55, 0xa5, 0xd4, 0x82, 0xc4, 0x0e, 0x30, 0xf6, 0x6a, 0x3a, 0xdd, 0x00, 0x63, 0xe9, 0x87, 0xd3,
	0x80, 0xc5, 0xde, 0x91, 0xf6, 0x53, 0x02, 0x79, 0x02, 0xc7, 0x5c, 0x04, 0x62, 0xce, 0xbd, 0x63,
	0x55, 0x0a, 0x23, 0x91, 0x8f, 0xa1, 0xa9, 0x1c, 0x46, 0xc6, 0x5a, 0x57, 0x56, 0x5b, 0xe9, 0xfa,
	0xda, 0xa5, 0x5c, 0x00, 0x6b, 0xb5, 0x00, 0xe4, 0x23, 0x80, 0x30, 0xc3, 0x40, 0x60, 0x34, 0x0a,
	0x84, 0xd7, 0x50, 0x37, 0x68, 0x18, 0x4d, 0x47, 0x48, 0xf3, 0x7c, 0x16, 0x2d, 0xcd, 0xa0, 0xcd,
	0x46, 0xa3, 0xcd, 0x11, 0xc6, 0x68, 0xcc, 0xb6, 0x36, 0x1b, 0x4d, 0x47, 0xd0, 0x5f, 0xe1, 0x68,
	0x90, 0xde, 0x61, 0x42, 0x3e, 0x01, 0xc7, 0x74, 0x63, 0x24, 0xa4, 0xc2, 0x54, 0xb7, 0x69, 0x94,
	0xb9, 0x53, 0x86, 0xe3, 0x0c, 0xf9, 0xad, 0x71, 0xd2, 0xc5, 0x6b, 0x1a, 0xa5, 0x72, 0xa2, 0x7f,
	0x80, 0x63, 0xba, 0x65, 0x18, 0xf2, 0x19, 0xd4, 0x58, 0x32, 0x4e, 0x55, 0x44, 0xbb, 0x7d, 0x7a,
	0x6e, 0xe8, 0x74, 0xbe, 0x6c, 0x8e, 0xaf, 0xcc, 0xe4, 0x53, 0x38, 0x2a, 0x82, 0xda, 0xed, 0x93,
	0xdc, 0x4f, 0x85, 0xf5, 0xb5, 0x91, 0x3a, 0x60, 0xdf, 0xb0, 0x78, 0x19, 0x9b, 0xf6, 0xe0, 0xb1,
	0xf4, 0xf2, 0x71, 0xc2, 0xb8, 0x90, 0xbf, 0x9a, 0x21, 0xef, 0x98, 0x72, 0x1b, 0x6d, 0x7a, 0x60,
	0xf7, 0x31, 0x89, 0xf6, 0x93, 0xf6, 0x73, 0xa8, 0x89, 0xc5, 0x4c, 0x83, 0x4f, 0xda, 0x8f, 0xf3,
	0x1c, 0x9d, 0x50, 0xb0, 0x34, 0x19, 0x2c, 0x66, 0xe8, 0x2b, 0x07, 0xca, 0xc0, 0xed, 0xde, 0x62,
	0x78, 0xd7, 0x4d, 0x23, 0xdc, 0x1f, 0x76, 0xcb, 0x99, 0xf2, 0x54, 0xd5, 0x7d, 0xa9, 0x42, 0x78,
	0xdf, 0x47, 0x91, 0x31, 0xbc, 0xc7, 0x9e, 0xe1, 0xcf, 0xff, 0x9a, 0xbe, 0xfc, 0x34, 0xd5, 0x52,
	0x85, 0x12, 0xb0, 0x7b, 0xc1, 0xa4, 0x7c, 0x95, 0x3b, 0x5c, 0x28, 0xb4, 0x09, 0x6c, 0x44, 0x09,
	0x9e, 0x05, 0x13, 0x7d, 0x15, 0xc7, 0x57, 0xdf, 0x72, 0x74, 0x62, 0x36, 0x65, 0x42, 0x45, 0x74,
	0x7c, 0x2d, 0x90, 0xa7, 0xd0, 0x60, 0x7c, 0xa4, 0x69, 0xa9, 0x06, 0xcd, 0xf2, 0x2d, 0xc6, 0xaf,
	0x95, 0x4c, 0x7f, 0x31, 0xbb, 0x84, 0x71, 0x51, 0xe6, 0x54, 0xcc, 0xb8, 0xbc, 0x4a, 0x75, 0x47,
	0x83, 0xa5, 0xb9, 0x58, 0x4e, 0x87, 0xe5, 0xe5, 0xf4, 0x14, 0xea, 0x43, 0x16, 0xc9, 0x78, 0xc5,
	0x5e, 0xa8, 0x3e, 0x77, 0xd4, 0x5e, 0xa0, 0x5f, 0xeb, 0xad, 0xa1, 0xac, 0xef, 0x96, 0xe5, 0xcb,
	0xdf, 0x01, 0x8a, 0x4e, 0x90, 0x53, 0x70, 0x96, 0x74, 0x1c, 0x49, 0x85, 0x5b, 0xd1, 0x2a, 0xdd,
	0x16, 0xad, 0x3a, 0x20, 0x27, 0x00, 0x6a, 0x4a, 0xb4, 0x7c, 0x48, 0xce, 0xc0, 0x7d, 0x21, 0x17,
	0x42, 0x47, 0x08, 0xe4, 0x42, 0x6b, 0xab, 0xed, 0x7f, 0x2c, 0x68, 0xaa, 0xa4, 0x7d, 0xcc, 0xee,
	0x59, 0x88, 0xa4, 0x0b, 0xcd, 0x8e, 0x6e, 0x9b, 0x42, 0x93, 0x0f, 0x56, 0xce, 0x54, 0xde, 0x92,
	0xad, 0x27, 0xb9, 0x69, 0x65, 0x1c, 0x69, 0x85, 0x5c, 0x40, 0xbd, 0xff, 0xba, 0x2f, 0x59, 0x4e,
	0xce, 0x72, 0xa7, 0x12, 0xe9, 0x5b, 0x85, 0xb6, 0x3c, 0x6b, 0x15, 0x72, 0x09, 0xd6, 0x72, 0x17,
	0x13, 0xaf, 0x40, 0xae, 0xae, 0xe7, 0xb7, 0x24, 0xbe, 0x86, 0x66, 0x79, 0x5a, 0xc9, 0x87, 0x2b,
	0xa7, 0x5f, 0x1b, 0xe2, 0x9d, 0xa7, 0xf8, 0x0e, 0x1a, 0xf2, 0xb0, 0xaa, 0x5c, 0x0f, 0xbc, 0xc0,
	0x2b, 0x70, 0xd7, 0xe7, 0x83, 0x3c, 0xcb, 0x7d, 0x77, 0x8c, 0xce, 0xce, 0x68, 0xdf, 0x82, 0xfd,
	0x13, 0x0a, 0x69, 0xba, 0x5a, 0xbc, 0x8c, 0xc8, 0x26, 0x3f, 0x5a, 0x9b, 0x2a, 0x5a, 0x21, 0x3f,
	0xe6, 0x30, 0x45, 0xb2, 0x22, 0x7a, 0x69, 0xaa, 0x5a, 0x6b, 0x8d, 0x2d, 0x71, 0x9f, 0x56, 0xc8,
	0x0f, 0xe0, 0x0e, 0xd5, 0x86, 0x57, 0xd4, 0xd0, 0x4f, 0xc8, 0x96, 0xec, 0xbb, 0xce, 0x7d, 0x01,
	0x50, 0xc0, 0x1f, 0x02, 0xfc, 0x1e, 0xac, 0x6b, 0x8c, 0xa5, 0x89, 0x13, 0xb7, 0x80, 0xe9, 0x59,
	0x6a, 0xb5, 0x72, 0xcd, 0xc6, 0xbf, 0x04, 0x5a, 0x21, 0x1d, 0x78, 0xe4, 0x63, 0x98, 0xde, 0x63,
	0xf6, 0x9f, 0x43, 0x5c, 0x82, 0xdd, 0x55, 0xef, 0x9e, 0x86, 0x9f, 0x6e, 0x94, 0x68, 0x0f, 0xbe,
	0x0d, 0xf6, 0x6f, 0x98, 0xb1, 0xf1, 0x42, 0xe3, 0xd7, 0x5e, 0x98, 0xed, 0xcd, 0xfa, 0x0a, 0x9a,
	0x7e, 0xe9, 0x75, 0xdb, 0x00, 0xad, 0xc9, 0xb4, 0x42, 0xae, 0xe0, 0xbd, 0xa2, 0xba, 0x2f, 0x4a,
	0x8f, 0xfc, 0x03, 0x0a, 0x7d, 0x09, 0x8d, 0xfc, 0xc9, 0x28, 0xcd, 0xf8, 0xfa, 0x33, 0xb2, 0x13,
	0xdf, 0x01, 0xb7, 0x44, 0xb1, 0xab, 0xc5, 0x90, 0x45, 0x5b, 0xaa, 0xfd, 0x36, 0x8e, 0xbd, 0x39,
	0x56, 0x7f, 0xfe, 0xbe, 0xf9, 0x37, 0x00, 0x00, 0xff, 0xff, 0xcf, 0x1c, 0x13, 0xe1, 0x0b, 0x0a,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NUserServiceClient is the client API for NUserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NUserServiceClient interface {
	//  账号登录
	AccountLogin(ctx context.Context, in *UserLoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	//  发送 短信
	SMSSend(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*NilResponse, error)
	//  账号登录-验证码
	SMSLogin(ctx context.Context, in *SMSLoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	//  注册
	UserRegister(ctx context.Context, in *UserRegisterRequest, opts ...grpc.CallOption) (*NilResponse, error)
	//  注册邮件验证发送邮件
	//  找回密码发送邮件验证
	SendEmail(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*NilResponse, error)
	//  找回密码 邮件或者电话 都可
	RetrievePassword(ctx context.Context, in *RetrievePasswordRequest, opts ...grpc.CallOption) (*NilResponse, error)
	//  根据id获取用户信息
	GetUserById(ctx context.Context, in *UserInfo, opts ...grpc.CallOption) (*UserInfo, error)
	//  批量获取用户信息 分页
	GetUserList(ctx context.Context, in *PageRequest, opts ...grpc.CallOption) (*UserListResponse, error)
	//  修改用户状态
	UpdateUserStatus(ctx context.Context, in *UserInfo, opts ...grpc.CallOption) (*NilResponse, error)
	//  修改用户信息
	UpdateUser(ctx context.Context, in *UserInfo, opts ...grpc.CallOption) (*NilResponse, error)
	//  批量删除用户
	DelUsers(ctx context.Context, in *UidList, opts ...grpc.CallOption) (*ChangeNumResponse, error)
	//  批量恢复用户
	RecoverDelUsers(ctx context.Context, in *UidList, opts ...grpc.CallOption) (*ChangeNumResponse, error)
	//  批量添加用户
	CreateUsers(ctx context.Context, in *UserList, opts ...grpc.CallOption) (*ChangeNumResponse, error)
	//  用户校验
	VerifyUsers(ctx context.Context, in *Token, opts ...grpc.CallOption) (*UserInfo, error)
	//  刷新token
	RefreshToken(ctx context.Context, in *Token, opts ...grpc.CallOption) (*Token, error)
	//  更新邮箱状态
	UpdateUserEmailStatus(ctx context.Context, in *UserInfo, opts ...grpc.CallOption) (*NilResponse, error)
	//  验证Code
	CheckCode(ctx context.Context, in *CheckCodeRequest, opts ...grpc.CallOption) (*NilResponse, error)
	//  根据Uid批量获取用户列表
	GetUserListByUid(ctx context.Context, in *UidList, opts ...grpc.CallOption) (*UserListResponse, error)
}

type nUserServiceClient struct {
	cc *grpc.ClientConn
}

func NewNUserServiceClient(cc *grpc.ClientConn) NUserServiceClient {
	return &nUserServiceClient{cc}
}

func (c *nUserServiceClient) AccountLogin(ctx context.Context, in *UserLoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/NUserPb.NUserService/AccountLogin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nUserServiceClient) SMSSend(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*NilResponse, error) {
	out := new(NilResponse)
	err := c.cc.Invoke(ctx, "/NUserPb.NUserService/SMSSend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nUserServiceClient) SMSLogin(ctx context.Context, in *SMSLoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/NUserPb.NUserService/SMSLogin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nUserServiceClient) UserRegister(ctx context.Context, in *UserRegisterRequest, opts ...grpc.CallOption) (*NilResponse, error) {
	out := new(NilResponse)
	err := c.cc.Invoke(ctx, "/NUserPb.NUserService/UserRegister", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nUserServiceClient) SendEmail(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*NilResponse, error) {
	out := new(NilResponse)
	err := c.cc.Invoke(ctx, "/NUserPb.NUserService/SendEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nUserServiceClient) RetrievePassword(ctx context.Context, in *RetrievePasswordRequest, opts ...grpc.CallOption) (*NilResponse, error) {
	out := new(NilResponse)
	err := c.cc.Invoke(ctx, "/NUserPb.NUserService/RetrievePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nUserServiceClient) GetUserById(ctx context.Context, in *UserInfo, opts ...grpc.CallOption) (*UserInfo, error) {
	out := new(UserInfo)
	err := c.cc.Invoke(ctx, "/NUserPb.NUserService/GetUserById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nUserServiceClient) GetUserList(ctx context.Context, in *PageRequest, opts ...grpc.CallOption) (*UserListResponse, error) {
	out := new(UserListResponse)
	err := c.cc.Invoke(ctx, "/NUserPb.NUserService/GetUserList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nUserServiceClient) UpdateUserStatus(ctx context.Context, in *UserInfo, opts ...grpc.CallOption) (*NilResponse, error) {
	out := new(NilResponse)
	err := c.cc.Invoke(ctx, "/NUserPb.NUserService/UpdateUserStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nUserServiceClient) UpdateUser(ctx context.Context, in *UserInfo, opts ...grpc.CallOption) (*NilResponse, error) {
	out := new(NilResponse)
	err := c.cc.Invoke(ctx, "/NUserPb.NUserService/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nUserServiceClient) DelUsers(ctx context.Context, in *UidList, opts ...grpc.CallOption) (*ChangeNumResponse, error) {
	out := new(ChangeNumResponse)
	err := c.cc.Invoke(ctx, "/NUserPb.NUserService/DelUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nUserServiceClient) RecoverDelUsers(ctx context.Context, in *UidList, opts ...grpc.CallOption) (*ChangeNumResponse, error) {
	out := new(ChangeNumResponse)
	err := c.cc.Invoke(ctx, "/NUserPb.NUserService/RecoverDelUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nUserServiceClient) CreateUsers(ctx context.Context, in *UserList, opts ...grpc.CallOption) (*ChangeNumResponse, error) {
	out := new(ChangeNumResponse)
	err := c.cc.Invoke(ctx, "/NUserPb.NUserService/CreateUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nUserServiceClient) VerifyUsers(ctx context.Context, in *Token, opts ...grpc.CallOption) (*UserInfo, error) {
	out := new(UserInfo)
	err := c.cc.Invoke(ctx, "/NUserPb.NUserService/VerifyUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nUserServiceClient) RefreshToken(ctx context.Context, in *Token, opts ...grpc.CallOption) (*Token, error) {
	out := new(Token)
	err := c.cc.Invoke(ctx, "/NUserPb.NUserService/RefreshToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nUserServiceClient) UpdateUserEmailStatus(ctx context.Context, in *UserInfo, opts ...grpc.CallOption) (*NilResponse, error) {
	out := new(NilResponse)
	err := c.cc.Invoke(ctx, "/NUserPb.NUserService/UpdateUserEmailStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nUserServiceClient) CheckCode(ctx context.Context, in *CheckCodeRequest, opts ...grpc.CallOption) (*NilResponse, error) {
	out := new(NilResponse)
	err := c.cc.Invoke(ctx, "/NUserPb.NUserService/CheckCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nUserServiceClient) GetUserListByUid(ctx context.Context, in *UidList, opts ...grpc.CallOption) (*UserListResponse, error) {
	out := new(UserListResponse)
	err := c.cc.Invoke(ctx, "/NUserPb.NUserService/GetUserListByUid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NUserServiceServer is the server API for NUserService service.
type NUserServiceServer interface {
	//  账号登录
	AccountLogin(context.Context, *UserLoginRequest) (*LoginResponse, error)
	//  发送 短信
	SMSSend(context.Context, *SendRequest) (*NilResponse, error)
	//  账号登录-验证码
	SMSLogin(context.Context, *SMSLoginRequest) (*LoginResponse, error)
	//  注册
	UserRegister(context.Context, *UserRegisterRequest) (*NilResponse, error)
	//  注册邮件验证发送邮件
	//  找回密码发送邮件验证
	SendEmail(context.Context, *SendRequest) (*NilResponse, error)
	//  找回密码 邮件或者电话 都可
	RetrievePassword(context.Context, *RetrievePasswordRequest) (*NilResponse, error)
	//  根据id获取用户信息
	GetUserById(context.Context, *UserInfo) (*UserInfo, error)
	//  批量获取用户信息 分页
	GetUserList(context.Context, *PageRequest) (*UserListResponse, error)
	//  修改用户状态
	UpdateUserStatus(context.Context, *UserInfo) (*NilResponse, error)
	//  修改用户信息
	UpdateUser(context.Context, *UserInfo) (*NilResponse, error)
	//  批量删除用户
	DelUsers(context.Context, *UidList) (*ChangeNumResponse, error)
	//  批量恢复用户
	RecoverDelUsers(context.Context, *UidList) (*ChangeNumResponse, error)
	//  批量添加用户
	CreateUsers(context.Context, *UserList) (*ChangeNumResponse, error)
	//  用户校验
	VerifyUsers(context.Context, *Token) (*UserInfo, error)
	//  刷新token
	RefreshToken(context.Context, *Token) (*Token, error)
	//  更新邮箱状态
	UpdateUserEmailStatus(context.Context, *UserInfo) (*NilResponse, error)
	//  验证Code
	CheckCode(context.Context, *CheckCodeRequest) (*NilResponse, error)
	//  根据Uid批量获取用户列表
	GetUserListByUid(context.Context, *UidList) (*UserListResponse, error)
}

// UnimplementedNUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedNUserServiceServer struct {
}

func (*UnimplementedNUserServiceServer) AccountLogin(ctx context.Context, req *UserLoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AccountLogin not implemented")
}
func (*UnimplementedNUserServiceServer) SMSSend(ctx context.Context, req *SendRequest) (*NilResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SMSSend not implemented")
}
func (*UnimplementedNUserServiceServer) SMSLogin(ctx context.Context, req *SMSLoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SMSLogin not implemented")
}
func (*UnimplementedNUserServiceServer) UserRegister(ctx context.Context, req *UserRegisterRequest) (*NilResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserRegister not implemented")
}
func (*UnimplementedNUserServiceServer) SendEmail(ctx context.Context, req *SendRequest) (*NilResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEmail not implemented")
}
func (*UnimplementedNUserServiceServer) RetrievePassword(ctx context.Context, req *RetrievePasswordRequest) (*NilResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrievePassword not implemented")
}
func (*UnimplementedNUserServiceServer) GetUserById(ctx context.Context, req *UserInfo) (*UserInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserById not implemented")
}
func (*UnimplementedNUserServiceServer) GetUserList(ctx context.Context, req *PageRequest) (*UserListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserList not implemented")
}
func (*UnimplementedNUserServiceServer) UpdateUserStatus(ctx context.Context, req *UserInfo) (*NilResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserStatus not implemented")
}
func (*UnimplementedNUserServiceServer) UpdateUser(ctx context.Context, req *UserInfo) (*NilResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (*UnimplementedNUserServiceServer) DelUsers(ctx context.Context, req *UidList) (*ChangeNumResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelUsers not implemented")
}
func (*UnimplementedNUserServiceServer) RecoverDelUsers(ctx context.Context, req *UidList) (*ChangeNumResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecoverDelUsers not implemented")
}
func (*UnimplementedNUserServiceServer) CreateUsers(ctx context.Context, req *UserList) (*ChangeNumResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUsers not implemented")
}
func (*UnimplementedNUserServiceServer) VerifyUsers(ctx context.Context, req *Token) (*UserInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyUsers not implemented")
}
func (*UnimplementedNUserServiceServer) RefreshToken(ctx context.Context, req *Token) (*Token, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshToken not implemented")
}
func (*UnimplementedNUserServiceServer) UpdateUserEmailStatus(ctx context.Context, req *UserInfo) (*NilResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserEmailStatus not implemented")
}
func (*UnimplementedNUserServiceServer) CheckCode(ctx context.Context, req *CheckCodeRequest) (*NilResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckCode not implemented")
}
func (*UnimplementedNUserServiceServer) GetUserListByUid(ctx context.Context, req *UidList) (*UserListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserListByUid not implemented")
}

func RegisterNUserServiceServer(s *grpc.Server, srv NUserServiceServer) {
	s.RegisterService(&_NUserService_serviceDesc, srv)
}

func _NUserService_AccountLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NUserServiceServer).AccountLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NUserPb.NUserService/AccountLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NUserServiceServer).AccountLogin(ctx, req.(*UserLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NUserService_SMSSend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NUserServiceServer).SMSSend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NUserPb.NUserService/SMSSend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NUserServiceServer).SMSSend(ctx, req.(*SendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NUserService_SMSLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SMSLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NUserServiceServer).SMSLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NUserPb.NUserService/SMSLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NUserServiceServer).SMSLogin(ctx, req.(*SMSLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NUserService_UserRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NUserServiceServer).UserRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NUserPb.NUserService/UserRegister",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NUserServiceServer).UserRegister(ctx, req.(*UserRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NUserService_SendEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NUserServiceServer).SendEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NUserPb.NUserService/SendEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NUserServiceServer).SendEmail(ctx, req.(*SendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NUserService_RetrievePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrievePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NUserServiceServer).RetrievePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NUserPb.NUserService/RetrievePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NUserServiceServer).RetrievePassword(ctx, req.(*RetrievePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NUserService_GetUserById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NUserServiceServer).GetUserById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NUserPb.NUserService/GetUserById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NUserServiceServer).GetUserById(ctx, req.(*UserInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _NUserService_GetUserList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NUserServiceServer).GetUserList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NUserPb.NUserService/GetUserList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NUserServiceServer).GetUserList(ctx, req.(*PageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NUserService_UpdateUserStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NUserServiceServer).UpdateUserStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NUserPb.NUserService/UpdateUserStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NUserServiceServer).UpdateUserStatus(ctx, req.(*UserInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _NUserService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NUserServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NUserPb.NUserService/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NUserServiceServer).UpdateUser(ctx, req.(*UserInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _NUserService_DelUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UidList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NUserServiceServer).DelUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NUserPb.NUserService/DelUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NUserServiceServer).DelUsers(ctx, req.(*UidList))
	}
	return interceptor(ctx, in, info, handler)
}

func _NUserService_RecoverDelUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UidList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NUserServiceServer).RecoverDelUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NUserPb.NUserService/RecoverDelUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NUserServiceServer).RecoverDelUsers(ctx, req.(*UidList))
	}
	return interceptor(ctx, in, info, handler)
}

func _NUserService_CreateUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NUserServiceServer).CreateUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NUserPb.NUserService/CreateUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NUserServiceServer).CreateUsers(ctx, req.(*UserList))
	}
	return interceptor(ctx, in, info, handler)
}

func _NUserService_VerifyUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Token)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NUserServiceServer).VerifyUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NUserPb.NUserService/VerifyUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NUserServiceServer).VerifyUsers(ctx, req.(*Token))
	}
	return interceptor(ctx, in, info, handler)
}

func _NUserService_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Token)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NUserServiceServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NUserPb.NUserService/RefreshToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NUserServiceServer).RefreshToken(ctx, req.(*Token))
	}
	return interceptor(ctx, in, info, handler)
}

func _NUserService_UpdateUserEmailStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NUserServiceServer).UpdateUserEmailStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NUserPb.NUserService/UpdateUserEmailStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NUserServiceServer).UpdateUserEmailStatus(ctx, req.(*UserInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _NUserService_CheckCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NUserServiceServer).CheckCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NUserPb.NUserService/CheckCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NUserServiceServer).CheckCode(ctx, req.(*CheckCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NUserService_GetUserListByUid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UidList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NUserServiceServer).GetUserListByUid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NUserPb.NUserService/GetUserListByUid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NUserServiceServer).GetUserListByUid(ctx, req.(*UidList))
	}
	return interceptor(ctx, in, info, handler)
}

var _NUserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "NUserPb.NUserService",
	HandlerType: (*NUserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AccountLogin",
			Handler:    _NUserService_AccountLogin_Handler,
		},
		{
			MethodName: "SMSSend",
			Handler:    _NUserService_SMSSend_Handler,
		},
		{
			MethodName: "SMSLogin",
			Handler:    _NUserService_SMSLogin_Handler,
		},
		{
			MethodName: "UserRegister",
			Handler:    _NUserService_UserRegister_Handler,
		},
		{
			MethodName: "SendEmail",
			Handler:    _NUserService_SendEmail_Handler,
		},
		{
			MethodName: "RetrievePassword",
			Handler:    _NUserService_RetrievePassword_Handler,
		},
		{
			MethodName: "GetUserById",
			Handler:    _NUserService_GetUserById_Handler,
		},
		{
			MethodName: "GetUserList",
			Handler:    _NUserService_GetUserList_Handler,
		},
		{
			MethodName: "UpdateUserStatus",
			Handler:    _NUserService_UpdateUserStatus_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _NUserService_UpdateUser_Handler,
		},
		{
			MethodName: "DelUsers",
			Handler:    _NUserService_DelUsers_Handler,
		},
		{
			MethodName: "RecoverDelUsers",
			Handler:    _NUserService_RecoverDelUsers_Handler,
		},
		{
			MethodName: "CreateUsers",
			Handler:    _NUserService_CreateUsers_Handler,
		},
		{
			MethodName: "VerifyUsers",
			Handler:    _NUserService_VerifyUsers_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _NUserService_RefreshToken_Handler,
		},
		{
			MethodName: "UpdateUserEmailStatus",
			Handler:    _NUserService_UpdateUserEmailStatus_Handler,
		},
		{
			MethodName: "CheckCode",
			Handler:    _NUserService_CheckCode_Handler,
		},
		{
			MethodName: "GetUserListByUid",
			Handler:    _NUserService_GetUserListByUid_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nuser.proto",
}
