{
 "title": "API",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "机房", "query": "prometheus" },
   { "name": "appname", "label": "应用名", "query": "label_values(go_info{},job)" },
   {
    "name": "instance",
    "label": "实例",
    "query": "label_values(go_info{job=~'$appname'},instance)"
   },
   {
    "name": "summarize",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "method",
    "label": "方法名",
    "query": "label_values(xmonitor_server_handle_seconds_count{job=~'$appname'},method) "
   }
  ]
 },
 "panels": [
  { "title": "服务端", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP Server错误码分布",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(xmonitor_server_handle_total{type=\"http\",method=~\"$method\",job=\"$appname\",code!=\"OK\"}[1m]))by(code,method,instance)",
     "legendFormat": "{{code}} | {{method}} | {{server}}"
    }
   ]
  },
  {
   "title": "HTTP Server QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(xmonitor_server_handle_seconds_count{type=\"http\",job=\"$appname\", method=~\"$method\"}[1m]))by(method, instance)",
     "legendFormat": "{{method}} | {{instance}}"
    }
   ]
  },
  {
   "title": "HTTP Server P99",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.99,irate(xmonitor_server_handle_seconds_bucket{type=\"http\", job=\"$appname\", method=~\"$method\"}[1m])>0)*1000)by(method,instance)",
     "legendFormat": "{{method}} | {{instance}}"
    }
   ]
  },
  {
   "title": "GRPC Server状态码分布",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(xmonitor_server_handle_total{type=\"unary\",method=~\"$method\",job=\"$appname\",code!=\"OK\"}[1m]))by(code,method,instance)",
     "legendFormat": "{{code}} | {{method}} | {{instance}}"
    }
   ]
  },
  {
   "title": "GRPC Server QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(xmonitor_server_handle_seconds_count{type=\"unary\",job=\"$appname\",method=~\"$method\"}[1m]))by(method,instance)",
     "legendFormat": "{{method}} | {{instance}}"
    }
   ]
  },
  {
   "title": "GRPC Server P99",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.99,irate(xmonitor_server_handle_seconds_bucket{type=\"unary\", job=\"$appname\",method=~\"$method\"}[1m])>0)*1000)by(method,instance)",
     "legendFormat": "{{method}} | {{instance}}"
    }
   ]
  }
 ]
}