{
 "title": "Instance",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "机房", "query": "prometheus" },
   { "name": "appname", "label": "应用名", "query": "label_values(go_info{},job)" },
   {
    "name": "instance",
    "label": "实例",
    "query": "label_values(go_info{job=~'$appname'},instance)"
   },
   {
    "name": "summarize",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "method",
    "label": "方法名",
    "query": "label_values(xmonitor_server_handle_seconds_count{job=~'$appname'},method) "
   }
  ]
 },
 "panels": [
  { "title": "概览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(up{job=\"$appname\",instance=~\"$instance\"})by(job)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}}",
     "measurement": "application.httprequests__active",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "实例数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"$appname\"})",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}}",
     "measurement": "application.httprequests__active",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "应用进程最大cpu",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "max((irate(process_cpu_seconds_total{instance=~\"$instance\",job=\"$appname\"}[1m])  ) * 100)"
    }
   ]
  },
  {
   "title": "应用进程最大进程驻留内存",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(process_resident_memory_bytes{instance=~\"$instance\",job=\"$appname\"})\n"
    }
   ]
  },
  {
   "title": "单一实例最大QPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(sum(irate(xmonitor_server_handle_seconds_count{job=\"$appname\",instance=~\"$instance\"}[1m])) by (instance))",
     "legendFormat": "{{$instance}}"
    }
   ]
  },
  {
   "title": "总 QPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(sum(irate(xmonitor_server_handle_seconds_count{job=\"$appname\"}[1m])) by (job)) ",
     "legendFormat": "总 QPS"
    }
   ]
  },
  {
   "title": "单一实例最大文件句柄数",
   "type": "singlestat",
   "description": "GC 持续时间",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(process_open_fds{job=~\"^($appname)$\",instance=~\"^($instance)$\"})by(job)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "实例", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "GC 耗时",
   "type": "graph",
   "description": "GC 持续时间",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(go_gc_duration_seconds{job=~\"^($appname)$\",instance=~\"^($instance)$\"})by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "QPS（多实例）",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_route",
     "expr": "sum(irate(xmonitor_server_handle_seconds_count{instance=~\"$instance\",job=~\"$appname\"}[1m]))by(instance)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "route" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}}",
     "measurement": "application.httprequests__transactions_per_endpoint",
     "select": [
      [
       { "params": [ "rate1m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "P99 耗时（多实例均值）",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_route",
     "expr": "avg(histogram_quantile(0.99,rate(xmonitor_server_handle_seconds_bucket{job=\"$appname\",instance=~\"$instance\"}[1m])>0)*1000)by(instance)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "route" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}}",
     "measurement": "application.httprequests__transactions_per_endpoint",
     "select": [
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "95th Percentile" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "实例文件句柄数 线性回归趋势",
   "type": "graph",
   "description": "文件句柄数线性回归趋势",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "deriv(process_open_fds{job=~\"^($appname)$\",instance=~\"^($instance)$\"}[30s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "应用进程CPU使用率（多实例）",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "max(irate(process_cpu_seconds_total{instance=~\"$instance\",job=\"$appname\"}[1m])*100)by(instance)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}}",
     "measurement": "application.httprequests__active",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "应用内存信息（多实例）",
   "type": "graph",
   "description": "Go程序占用的常驻内存和虚拟内存容量",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(go_memstats_alloc_bytes{instance=~\"$instance\",job=\"$appname\"})by(instance)",
     "legendFormat": "memstats_alloc | {{instance}} "
    },
    {
     "expr": "sum(go_memstats_heap_inuse_bytes{job=~\"^($appname)$\",instance=~\"^($instance)$\"})by(instance)",
     "legendFormat": "heap_inuse | {{instance}} "
    },
    {
     "expr": "sum(go_memstats_stack_inuse_bytes{job=~\"^($appname)$\",instance=~\"^($instance)$\"})by(instance)",
     "legendFormat": " stack_inuse | {{instance}}"
    },
    {
     "expr": "sum(go_memstats_sys_bytes{job=~\"^($appname)$\",instance=~\"^($instance)$\"})by(instance)",
     "legendFormat": "memstats_sys | {{instance}} "
    },
    {
     "expr": "sum(process_resident_memory_bytes{job=~\"^($appname)$\",instance=~\"^($instance)$\"})by(instance)",
     "legendFormat": "总进程驻留内存 | {{instance}}  "
    }
   ]
  },
  {
   "title": "各实例错误代码趋势",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_route",
     "expr": "rate(xmonitor_server_error_total{instance=~\"$instance\",job=\"$appname\"}[1m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "route" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}}",
     "measurement": "application.httprequests__one_minute_error_percentage_rate_per_endpoint",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$environment$/" }
     ]
    }
   ]
  },
  {
   "title": "Go Goroutines（多实例）",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(go_goroutines{instance=~\"$instance\",job=\"$appname\"})by(instance)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}}",
     "measurement": "application.httprequests__active",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "实例文件句柄数（多实例）",
   "type": "graph",
   "description": "文件句柄数",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{job=~\"^($appname)$\",instance=~\"^($instance)$\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "服务端", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "HTTP Server错误码分布",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(xmonitor_server_handle_total{type=\"http\",instance=~\"$instance\",job=\"$appname\",code!=\"OK\"}[1m]))by(code,method,instance)",
     "legendFormat": "{{code}} | {{method}} | {{server}}"
    }
   ]
  },
  {
   "title": "HTTP Server QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(xmonitor_server_handle_seconds_count{type=\"http\",instance=~\"$instance\",job=\"$appname\"}[1m]))by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HTTP Server P99",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 23 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.99,irate(xmonitor_server_handle_seconds_bucket{type=\"http\",instance=~\"$instance\", job=\"$appname\"}[1m])>0)*1000)by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GRPC Server状态码分布",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(xmonitor_server_handle_total{type=\"unary\",instance=~\"$instance\",job=\"$appname\",code!=\"OK\"}[1m]))by(code,method,instance)",
     "legendFormat": "{{code}} | {{method}} | {{instance}}"
    }
   ]
  },
  {
   "title": "GRPC Server QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(xmonitor_server_handle_seconds_count{type=\"unary\",instance=~\"$instance\",job=\"$appname\"}[1m]))by(instance)",
     "legendFormat": " {{instance}}"
    }
   ]
  },
  {
   "title": "GRPC Server P99",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 30 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.99,irate(xmonitor_server_handle_seconds_bucket{type=\"unary\",instance=~\"$instance\", job=\"$appname\"}[1m])>0)*1000)by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}