apiVersion: v1
kind: Service
metadata:
  name: k8s-ndisk-server-authority
  namespace: ndisk
spec:
  type: NodePort
  selector:
    name: authority
    version: v1
  ports:
  - name: http
    port: 80
    targetPort: 80 

