[server]
    locale = "zh"

[app]
    name="ndisk_nuser"
    debug= true
    version="v0.1.0"

[mysql.main]
    host = "127.0.0.1"
    username = "root"
    password = "root"
    dbName = "ndisk_nuser"
    type = "mysql"
    port = "3306"
    debug = true

[redis.main]
    addr="127.0.0.1:6379"

[email.main]
    host="smtp.yeah.net"
    port=465
    username="yangzzzzzz@yeah.net"
    password=""

[sms.main]
    area="cn-hangzhou"
    accessKeyId=""
    accessSecret=""

[rpc]
    serverIp = "127.0.0.1"
    serverPort = 8090
    serverTimeout="10s"
    serverSlowThreshold= "8s"
    register_etcd_addr = "127.0.0.1:2379"
    register_ttl = "10s"
    register_interval = "3s"

[xlog]
    name = "ndisk_nuser.log"
    dir = "."
    level = ""
    async = false
    debug = true
    add_caller= true
    caller_skip=2

[app.govern]
    host = "127.0.0.1"
    port = 4569

