[server]
    locale = "zh"

[app]
    name="ndisk_nuser"
    debug= true
    version="v0.1.0"

[mysql.main]
    tablePrefix = "ndisk"
    host = "127.0.0.1"
    username = "root"
    password = "root"
    dbName = "ndisk_nuser"
    type = "mysql"
    port = "3306"
    debug = true

[rpc]
    etcd_addr="127.0.0.1:2379"
    ip="0.0.0.0"
    port=8484
    register_ttl="10s"
    register_interval="3s"

[xlog]
    name = "ndisk_nuser.log"
    dir = "."
    level = ""
    async = false
    debug = true
    add_caller= true
    caller_skip=2

[app.govern]
    host = "127.0.0.1"
    port = 4569

