[server]
    addr = "0.0.0.0:1123"
    locale = "zh"

[app]
    name="ndisk_getway"
    debug= true
    version="v0.1.0"

[xlog]
    name = "log.log"
    dir = "."
    level = ""
    async = false
#    debug = true
    add_caller= true
    caller_skip=2

[app.govern]
    host = "127.0.0.1"
    port = 4568

[email.main]
    host="smtp.yeah.net"
