[server]
    addr = "0.0.0.0:1123"
    locale = "zh"

[app]
    name="ndisk_getway"
    debug= true
    version="v0.1.0"

[xlog]
    name = "ndisk_getway.log"
    dir = "."
    level = ""
    async = false
    debug = true
    add_caller= true
    caller_skip=2

[app.govern]
    host = "0.0.0.0"
    port = 4568

[rpc]
    serverTimeout="10s"
    serverSlowThreshold= "8s"
    register_etcd_addr = "127.0.0.1:2379"
    register_ttl = "10s"
    register_interval = "3s"

[trace.jaeger]
